---
parser: "babel-eslint"
extends: "airbnb"
plugins:
  - "react"
  - "flowtype"
  - "flow-vars"
rules:
  "flowtype/require-parameter-type": 2
  "flow-vars/define-flow-type": 1
  "flow-vars/use-flow-type": 1
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
